version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reddit-frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      reddit_net:
        ipv4_address: 172.60.0.4
  
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: reddit-database
    networks:
      reddit_net:
        ipv4_address: 172.60.0.6
    environment:
      - MYSQL_DATABASE=Botustech
      - MYSQL_USER=botus
      - MYSQL_PASSWORD=botus1234
      - MYSQL_ROOT_PASSWORD=boturoot
    volumes:
      - /mounts/mysql:/var/lib/mysql

  redis:
    image: redis:6.2.1
    restart: unless-stopped
    container_name: botus_redis
    networks:
      reddit_net:
        ipv4_address: 172.60.0.7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../mounts/redis/:/data

  backend:
    container_name: reddit-backend
    build:
      context: ./backend/botustech
      dockerfile: Dockerfile
    networks:
      reddit_net:
        ipv4_address: 172.60.0.5
    restart: always
    ports:
      - 8000:8000
    depends_on:
     - db
     - redis
    command: ./entrypoint.sh

networks:
  reddit_net:
    name: reddit-network
    ipam:
      config:
        - subnet: 172.60.0.1/24