version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reddit-frontend
    restart: always
    environment:
      - HTTPS=true
    networks:
      reddit_net:
        ipv4_address: 172.60.0.4
  
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: reddit-database
    environment:
      - MYSQL_DATABASE=Botustech
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - reddit_net

  redis:
    image: redis:6.2.1
    restart: unless-stopped
    container_name: reddit-reddis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../mounts/redis/:/data
    networks:
      - reddit_net

  backend:
    container_name: reddit-backend
    build:
      context: ./backend/botustech
      dockerfile: Dockerfile
    networks:
      reddit_net:
        ipv4_address: 172.60.0.5
    restart: always
    depends_on:
     - db
     - redis
    command: bash -c "python manage.py migrate && gunicorn botustech.wsgi:application --bind 0.0.0.0:8000"

networks:
  reddit_net:
    name: reddit-network
    ipam:
      config:
        - subnet: 172.60.0.1/24