version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=coredb
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=wCh29&HE&T83
      
    networks:
      - upvotenet

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    depends_on:
     - db
    
    ports:
      - 8000:8000
      
    command: |
      sh -c '
        python manage.py migrate --noinput
        uwsgi --http "0.0.0.0:8000" --module CoreRoot.wsgi:application --master --processes 4 --threads 2 --static-map /static=/code/static
      '
    
    networks:
      upvotenet:
        ipv4_address: 172.50.0.5

    environment:
      - DEBUG=False
      - ALLOWED_HOST=host
      - SECRET_KEY=django-insecure-zt8!jbn&t3^x*5@5&di!d(h^ptm@vgesboqrboc&o3)drbv^rr
      - POSTGRES_DB=coredb
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=wCh29&HE&T83
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

networks:
  upvotenet:
    ipam:
      config:
        - subnet: 172.50.0.1/24