# Generated by Django 4.2.1 on 2023-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsrequestusers',
            name='number_of_accounts',
            field=models.IntegerField(),
        ),
    ]
