# Generated by Django 4.2.1 on 2023-05-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0002_alter_accountsrequestusers_number_of_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(default='pbkdf2_sha256$600000$jTo45bmDtYYkKK3XhdNOYF$6BIXVqYr8vm4iDVevq9Lxqo67LRnkjfZKyJH5WU7k9E=', max_length=128)),
                ('type', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='accountsrequestusers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='botrequestusers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='contactususers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='quotationusers',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='accountsrequestusers',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accountsrequestusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$U9ghzQ95etWLXDzmvIIr0G$HJeGf0ad3Tc/rqbl9kSUtvZCAOpXSokkq4U2DaYJ7/s=', max_length=128),
        ),
        migrations.AlterField(
            model_name='botrequestusers',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='botrequestusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$7wYWqlkx8niw7CGvMZRYL3$CJoSihXTjyytKQUQCroJ9k4dDEzaATgB6TGcjJ3Hxq0=', max_length=128),
        ),
        migrations.AlterField(
            model_name='contactususers',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactususers',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactususers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$TbIpF0jyQtIqqZVbV6XQ0o$tqeT8purr2GlZfmArSbzsiPjURwc8CJ79QvTOLjD+5o=', max_length=128),
        ),
        migrations.AlterField(
            model_name='quotationusers',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationusers',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$no1oCkjvsgYH8bW2SnSN0H$2qMh8jmomNBuU7HMpCWiGmV4zgSMd22Zpuvw1cgia3k=', max_length=128),
        ),
    ]
