# Generated by Django 4.2.1 on 2023-07-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0003_waitlistusers_remove_accountsrequestusers_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('isadmin', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUsUsers',
        ),
        migrations.AlterField(
            model_name='accountsrequestusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$AhJqtDP9ayHOQsLvSPbTu8$iQFmn0VhymSOfOLWxdh0jWA4uCXQCZzvQzo2IUom5lQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='botrequestusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Xk1wOA5UAIrgsfgNfxAKqb$1ZmhTfOKSWP5iVcHBRLjjHG4yrxb9mOBHcEXtVuoiyQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='quotationusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$dVID46Gg1H1h8bANpdpv7T$4wZkztBNKVZ84L0uPq3dkJaPTsgxf5tmnvQVIJeNgGs=', max_length=128),
        ),
        migrations.AlterField(
            model_name='waitlistusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$XDeg6EisW63jt3HyDbF1c6$/HkOnkCt4Q+zRu5Gikoy0ZVX4hb7Hnv8ODJKwg1YkA8=', max_length=128),
        ),
    ]
