# Generated by Django 4.2.1 on 2023-07-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0005_alter_accountsrequestusers_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsrequestusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$mPSPATHjYAW7wdrvrB265R$IsB0cuOztJx39BnHHNdU+P6BIDfz47dkg281gYACbw8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='botrequestusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$wfWNOiFyJcYtkqohmp43sv$S8Xyr2QJuSCpnlz7gRjm3mN9Ww4KsEglj0zHUdjFK2s=', max_length=128),
        ),
        migrations.AlterField(
            model_name='quotationusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ElVa8yQTIEIFFnwRRiiJrn$jtG1MHMQSoBfwI9uUEgI/LKQA+y5pIJ7ArpX5XGgNSI=', max_length=128),
        ),
        migrations.AlterField(
            model_name='waitlistusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$gYmUIFg9ign5RtsGHOVqdc$yRukpwEh9gdktMMdOlMsXkfOJtQ8qBffJMiwzCXpdd8=', max_length=128),
        ),
    ]
