# Generated by Django 4.2.1 on 2023-07-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0006_alter_accountsrequestusers_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsrequestusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$vttAHj2SkJNMcFf8WKK1vT$BKvYm+pheXYiEYJV7yv4E+8K21boBjmKzK6fmFNA89A=', max_length=128),
        ),
        migrations.AlterField(
            model_name='botrequestusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$eFBD3Pr6q2oiot7VCvXiuS$LMnkt6gTOWRexhP/CJjIrsgMkSut2QileKpqAfB0PAQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='quotationusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$xFnA6au2GeyLGTR51t92jL$8cbf8LWq5VlhJh1PTN1bZBCM8UXyjoWV1SuH5hh7dGE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='waitlistusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Z29NvbFZZE8xCRUIYd0XMM$9TBbl1RkUP6GXNYx1UV972i//QKwgo4fuYnCC4cTN9E=', max_length=128),
        ),
    ]
