# Generated by Django 4.2.1 on 2023-07-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0007_alter_accountsrequestusers_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUser',
            new_name='RegisteredUsers',
        ),
        migrations.DeleteModel(
            name='QuotationUsers',
        ),
        migrations.AlterField(
            model_name='accountsrequestusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$GKHWGm6lTjhLjKP3m63lEV$aUKXwdgagY5FNIoj7YMl73CLWrTwe3akQkB78K95CDE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='botrequestusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$vGIBF9wpcphAB3HmRQt6iU$Rq8SDyDzOF7rt2fQz1/x0heV8nWbmok689vPf66GZL8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='waitlistusers',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$kos7g57d83RZoucyskOHC7$smbQpX+4bQL1Afht3wtDyJIUvV8mg+ACsRHtpOWVxys=', max_length=128),
        ),
    ]
