# Generated by Django 4.2.1 on 2023-07-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0008_rename_createuser_registeredusers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('action', models.EmailField(max_length=255, unique=True)),
                ('number', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botustech.registeredusers')),
            ],
        ),
        migrations.DeleteModel(
            name='AccountsRequestUsers',
        ),
        migrations.DeleteModel(
            name='BotRequestUsers',
        ),
        migrations.DeleteModel(
            name='WaitlistUsers',
        ),
    ]
