# Generated by Django 4.2.1 on 2023-07-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0010_alter_redditurls_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='totalvotes',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
