# Generated by Django 4.2.1 on 2023-07-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0011_registeredusers_totalvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='totalcomments',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='totalspent',
            field=models.CharField(default=0.0, max_length=128),
            preserve_default=False,
        ),
    ]
