# Generated by Django 4.2.1 on 2023-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0012_registeredusers_status_registeredusers_totalcomments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proxies', models.EmailField(max_length=255, unique=True)),
                ('voted', models.CharField(max_length=255)),
                ('commented', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
