# Generated by Django 4.2.1 on 2023-07-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0013_redditaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditaccounts',
            name='proxies',
            field=models.EmailField(max_length=255),
        ),
    ]
