# Generated by Django 4.2.1 on 2023-07-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botustech', '0014_alter_redditaccounts_proxies'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='package',
            field=models.CharField(default='None', max_length=124),
            preserve_default=False,
        ),
    ]
